export const incidentTypes = [
  { id: 1, type: 'PRESUNTAS ACTIVIDADES CONTRA LA VIDA EL CUERPO Y LA SALUD' },
  { id: 2, type: 'PRESUNTA ACTIVIDAD CONTRA LA LIBERTAD' },
  { id: 3, type: 'PRESUNTAS ACTIVIDADES CONTRA EL PATRIMONIO' },
  { id: 4, type: 'PRESUNTAS ACTIVIDADES CONTRA LA SEG. PUB.' },
  { id: 5, type: 'PRE. ACTIV.CONTRA LA SALUD PUB.' },
  { id: 6, type: 'PRE. ACTIV. AMBIENTALES' },
  { id: 7, type: 'PRESUNTA ACTIVIDAD CONTRA LA TRANQUILIDAD PUB' },
  { id: 8, type: 'PRESUNTAS ACTIV. CONTRA LA ADM. PUB.' },
  { id: 9, type: 'PRE. ACTIV. CONTRA LOS PODERES DEL ESTADO' },
  { id: 10, type: 'PRESUNTA ACTIV. CONTRA LA PERSONA' },
  { id: 11, type: 'PRESUNTA ACTIV. CONTRA EL PATRIMONIO' },
  { id: 12, type: 'PRE. ACTIV. CONTRA LA SEG. PÚBLICA' },
  { id: 13, type: 'PRESUNTA ACTIV. CONTRA LAS BUENAS COSTUMBRES' },
  { id: 14, type: 'PRESUNTA ACTIV. CONTRA LA TRANQUIL. PUB.' },
  {
    id: 15,
    type: 'PRESUNTOS ACCIDENTES E INFRACCIONES AL TRÁNSITO Y TRANSPORTE',
  },
  {
    id: 16,
    type: 'PRESUNTA ACTIV. CONTRA LA LEY DE PROTEC. Y BIENESTAR ANIMAL',
  },
  {
    id: 17,
    type: 'PRESUNTA ACTIV. DE PERSONAS QUE AFECTAN TRANQUILIDAD Y EL ORDEN',
  },
  {
    id: 18,
    type: 'PRESUNTAS INFRACCIONES A LAS ORDENANZAS Y LICENCIAS MUNICIPALES',
  },
  { id: 19, type: 'AYUDA, AUXILIO Y RESCATE DE PERSONAS' },
  { id: 20, type: 'APOYO A OTRAS GERENCIAS O AREAS DE LA MUNICIPALIDAD' },
  { id: 21, type: 'APOYO A OTRAS ENTIDADES' },
  { id: 22, type: 'DESASTRES' },
  { id: 23, type: 'INFRAESTRUCTURA Y SERVICIOS ESENCIALES AFECTADOS' },
  { id: 24, type: 'ESPACIOS PÚBLICOS EN RIESGO' },
  { id: 25, type: 'PRESUNTOS ACONTECIMIENTOS ESPECIALES' },
  { id: 26, type: 'OPERATIVO MUNICIPAL' },
  { id: 27, type: 'ESTRATEGIAS Y OPERATIVOS ESPECIALES' },
];

export const incidentSubTypes = [
  {
    typeId: 1,
    subtypes: [
      'PRESUNTO HOMICIDIO',
      'PRESUNTO FEMINICIDIO',
      'PRESUNTO SICARIATO',
      'PRESUNTAS LESIONES LEVES Y GRAVES',
      'PRESUNTA EXPOSICION A PELIGRO O ABANDONO DE PERSONAS (EXPOSICION, ABANDONO, OMISION DE SOCORRO Y AUXILIO).',
    ],
  },
  {
    typeId: 2,
    subtypes: [
      'PRESUNTO CONTRA LA LIBERTAD PERSONAL (ACOSO, SECUESTRO)',
      'PRESUNTA TRATA DE PERSONAS',
      'PRESUNTA VIOLACION LIBERTAD SEXUAL (MAYOR Y MENOR DE EDAD, SEDUCCION, PORNOGRAFIA, TOCAMIENTOS, ACOSO, EXHIBICIONISMO Y CHANTAJE)',
      'OTROS PRESUNTOS (LA INTIMIDAD, VIOLACION DE DOMICILIO, COMUNICACIONES, SECRETO PROFESIONAL, DE REUNION, TRABAJO, EXPRESION, PROXENETISMO Y OFENSAS AL PUDOR)',
    ],
  },
  {
    typeId: 3,
    subtypes: [
      'PRESUNTO ROBO A PERSONAS (CELULARES, MOCHILAS, CARTERAS, BILLETERAS, RELOJES, JOYAS Y OTROS)',
      'PRESUNTO ROBO DE CASA HABITADA',
      'PRESUNTO ROBO DE GANADO (ABIGEATO)',
      'PRESUNTO ROBO A EMPRESAS PARTICULARES Y ESTATALES',
      'PRESUNTO ROBO DE VEHÍCULOS (MAYORES Y MENORES)',
      'PRESUNTO ROBO DE ACCESORIOS Y AUTOPARTES',
      'PRESUNTO ROBO A PASAJEROS EN VEHICULOS DE TRANSPORTE Y MERCANCIAS EN VEHICULOS DE CARGA Y REPARTIDORES',
      'PRESUNTO DAÑO (DAÑAR, DESTRUIR O INUTILIZAR BIEN MUEBLE O INMUEBLE)',
      'PRESUNTO HURTO A PERSONAS (CELULARES, MOCHILAS, CARTERAS, BILLETERAS, RELOJES, JOYAS Y OTROS)',
      'HURTO DE CASA HABITADA',
      'PRESUNTO HURTO DE GANADO (ABIGEATO)',
      'PRESUNTO HURTO A EMPRESAS PARTICULARES Y ESTATALES',
      'PRESUNTO HURTO DE VEHÍCULOS (MAYORES Y MENORES)',
      'PRESUNTO HURTO A PASAJEROS EN VEHICULOS DE TRANSPORTE Y MERCANCIAS EN VEHICULOS DE CARGA Y REPARTIDORES',
      'PRESUNTO OTROS (RECEPTACION, APROPIACION ILICITA, ESTAFA, EXTORSION, CHANTAJE Y USURPACION DE INMUEBLE)',
    ],
  },
  {
    typeId: 4,
    subtypes: [
      'PRESUNTO PELIGRO COMUN (CREAR INCENDIO O EXPLOSION, CONDUCCION O MANIPULACION EN ESTADO DE EBRIEDAD O DROGADICCIÓN, FABRICACIÓN, TRAFICO O TENECIA DE ARMAS, EXPLOSIVOS Y PIROTECNICOS)',
      'PRESUNTO CONTRA EL TRANSPORTE (CONTRA LA SEGURIDAD COMUN Y ENTORPECIMIENTO DEL SERVICIO)',
    ],
  },
  {
    typeId: 5,
    subtypes: [
      'PRESUNTA CONTAMINACION Y PROPAGACION (CONTAMINACION DE AGUAS, ADULTERACION DE SUSTANCIAS Y COMERCIALIZACION DE PRODUCTOS NOCIVOS)',
      'PRESUNTO TRAFICO ILICITO DE DROGAS (PROMOCION, FAVORECIMIENTO, COMERCIALIZACION, PRODUCCION, MICROCOMERCIALIZACION AND POSESION).',
    ],
  },
  {
    typeId: 6,
    subtypes: [
      'PRESUNT ACTIVIDAD CONTRA LOS RECURSOS NATURALES Y MEDIO AMBIENTE (CONTAMINACION, RESIDUOS PELIGROSOS Y MINERIA ILEGAL)',
      'PRESUNTA ACTIVIDAD CONTRA LOS RECURSOS NATURALES (TRAFICO ILEGAL DE ESPECIES ACUATICAS, FLORA Y FAUNA, TALA ILEGAL Y DEFORESTACON DE BOSQUES)',
    ],
  },
  {
    typeId: 7,
    subtypes: [
      'PRESUNTA ACTIVIDAD CONTRA LA PAZ PUBLICA (DISTURBIOS, APOLOGIA, ORG. CRIMINAL, BANDA Y REGLAJE O MARCAJE)',
      'PRESUNTA ACTIVIDAD TERRORISTA (PROVOCA, CREA O MANTIENE ESTADO OF ZOZOBRA, ALARMA O TERROR A LA POBLACION)',
      'OTROS PRESUNTOS (DISCRIMINACION, CONTRA LA HUMANIDAD, GENOCIDIO, DESAPARICION FORZADA Y TORTURA)',
    ],
  },
  {
    typeId: 8,
    subtypes: [
      'COMETIDOS POR FUNCIONARIOS PÚBLICOS (ABUSO DE AUTORIDAD, MALVERSACIÓN, OTROS)',
      'COMETIDOS POR PARTICULARES (USURPACION OF AUTORIDAD, VIOLENCIA Y RESISTENCIA, OTROS)',
    ],
  },
  {
    typeId: 9,
    subtypes: [
      'REBELION (ALZARSE EN ARMAS), SEDICION (DESCONOCER AL GOBIERNO) Y MOTIN (EMPLEAR LA VIOLENCIA Y ATRIBUIRSE DERECHOS DEL PUEBLO Y HACER PETICIONES EN NOMBRE DE ESTE)',
    ],
  },
  {
    typeId: 10,
    subtypes: [
      'PRESUNTAS LESIONES (MUY LEVES)',
      'PRESUNTO MALTRATO (SIN LESIÓN)',
      'PRESUNTAS PELEAS CALLEJERAS CON LESIONES MUY LEVES O SIN LESIONES',
      'PRESUNTA MORDEDURA CANINA, PATADA DE CABALLO O LESIÓN DE ANIMAL DOMESTICO',
    ],
  },
  {
    typeId: 11,
    subtypes: [
      'PRESUNTO HURTO SIMPLE. NO SOBREPASE RMV (S/. 1025.00 - DS. Nº 003-2022-TR DEL 02ABR2022)',
      'PRESUNTO DAÑO A LA PROPIEDAD MUEBLE O INMUEBLE',
      'PRESUNTO HURTO FAMÉLICO (CONSUMIR Y NO PAGAR)',
      'PRESUNTA USURPACION BREVE Y JUEGOS PROHIBIDOS.',
    ],
  },
  {
    typeId: 12,
    subtypes: [
      'ARROJO DE BASURA O QUEMARLA CAUSANDO MOLESTIAS',
      'PRESUNTA OBSTRUCCIÓN Y ARROJO DE ESCOMBROS Y/O MATERIALES. TAMBIEN NO COLOCAR SEÑALES PREVENTIVAS EN LA VIA.',
      'CONDUCIR VEHÍCULO NO MOTORIZADO O ANIMAL A EXCESIVA VELOCIDAD /O CONFIAR VEHICULO A MENOR DE EDAD O INEXPERTO',
    ],
  },
  {
    typeId: 13,
    subtypes: [
      'PRESUNTO CONSUMO DE ALCOHOL O DROGAS PERTURBANDO LA TRANQUILIDAD O SEGURIDAD DE LAS PERSONAS O SUMINISTRARLO A MENORES DE EDAD.',
      'PRESUNTA DESTRUCCIÓN DE PLANTAS',
      'PRESUNTO ACTOS DE CRUELDAD CONTRA LOS ANIMALES',
      'PRESUNTA PROPOSICION INMORAL O DESHONESTA',
    ],
  },
  {
    typeId: 14,
    subtypes: [
      'PERTURBAR ACTOS SOLEMNES O REUNIONES PÚBLICAS',
      'FALTAMIENTO DE PALABRA A UNA AUTORIDAD',
      'OCULTAR SU NOMBRE, DOMICILIO O ESTADO CIVIL A LA AUTORIDAD',
      'EL QUE NIEGA AUXILIO A UNA AUTORIDAD PARA SOCORRER A UN TERCERO',
      'PERTURBAR CON DISCUSIONES RUIDOS O MOLESTIAS ANALOGAS',
    ],
  },
  {
    typeId: 15,
    subtypes: [
      'PRESUNTO ATROPELLO',
      'PRESUNTO ATROPELLO Y FUGA',
      'PRESUNTO CHOQUE',
      'PRESUNTO CHOQUE Y FUGA',
      'OTROS PRESUNTOS ACCIDENTES (DESPISTE, VOLCADURA, CAIDA DE PASAJERO E INCENDIO)',
      'APOYO SUBSIDIARIO A LA PNP, PARA EL CONTROL DE TRANSITO VEHICULAR CUANDO LO SOLICITE',
      'PRESUNTO VEHÍCULO ABANDONADO',
      'VEHÍCULOS NO AUTORIZADOS O PROHIBIDOS PARA SERVICIO PÚBLICO',
      'VEHÍCULOS QUE HACEN PIQUES Y CARRERAS.',
      'PARADEROS Y VEHÍCULOS DE TRANSPORTE PÚBLICO INFORMALES',
      'VEHÍCULOS ESTACIONADOS EN ZONA PROHIBIDA',
      'OTRAS INFRACCIONES AL RGTO. DE TRÁNSITO.',
    ],
  },
  {
    typeId: 16,
    subtypes: [
      'LEY Nº 30407 - ANIMALES SENSIBLES, DOMESTICOS, DE GRANJA, SILVESTRES Y ACUÁTICOS Y ANIMALES DE COMPAÑIA O MASCOTAS. (ABANDONO DE ANIMALES EN LA VIA PUBLICA - UTILIZACION DE ANIMALES EN ESPECTACULOS DE ENTRETENIMIENTO PUBLICO O PRIVADO - LA TENENCIA, CAZA, CAPTURA, COMPRA Y VENTA PARA EL CONSUMO HUMAN OF ESPECIES ANIMALES NO DEFINIDAS COMO ANIMALES DE GRANJA, EXCEPTUÁNDOSE AQUELLAS SILVESTRES CRIADAS EN ZOOCRIADEROS O PROVENIENTES DE AREAS DE MANEJO AUTORIZADAS Y PELEAS DE ANIMALES TANTO DOMESTICOS COMO SILVESTRES EN LUGARES PUBLICOS O PRIVADOS)',
    ],
  },
  {
    typeId: 17,
    subtypes: [
      'CAMBISTAS EN LA VÍA PÚBLICA (INTERRUMPEN TRÁNSITO PEATONAL Y VEHÍCULAR)',
      'LLAMADORES, JALADORES Y PARQUEADORES INFORMALES (QUE GRITAN Y SE APROPIAN DE ESPACIOS PUBLICOS)',
      'RECICLADORES FORMALES O INFORMALES',
      'ORATES Y/O INDIGENTES (AGRESIVOS, QUE EXIGEN DINERO O SE POSESIONAN DE ESPACIOS, INTERRUMPIENDO ACTIVIDADES PUBLICAS O PRIVADAS)',
      'PRESUNTAS PERSONAS EN ACTITUD SOSPECHOSA',
      'PRESUNTAS PERSONAS EN VEHÍCULOS SOSPECHOSOS',
      'PRESUNTOS TRABAJADORES SEXUALES EN LA VIA PÙBLICA (MASCULINO O FEMENINO)',
      'PRESUNTAS PERSONAS QUE MICCIONAN EN VIA PÚBLICA',
      'OTROS PRESUNTOS (ESPECIFICAR EN LA SECCIÓN DATOS IMPORTANTES DEL FORMATO DE OCURRENCIAS)',
    ],
  },
  {
    typeId: 18,
    subtypes: [
      'COMERCIO EN VÍA PÚBLICA DISTINTA AL AUTORIZADO',
      'COMERCIO EN VÍA PÚBLICA NO AUTORIZADO',
      'COMERCIO SIN LICENCIA DE FUNCIONAMIENTO',
      'CONSTRUCCIONES SIN LICENCIA MUNICIPAL',
      'TRABAJO SEXUAL CLANDESTINO EN INMUEBLE (SALA DE MASAJES, SAUNAS Y OTROS)',
      'ESTABLECIMIENTOS EN MALAS CONDICIONES OF LIMPIEZA',
      'RUIDOS MOLESTOS',
      'OBSTRUCCION DE CALZADA, VEREDA Y OTROS, SIN INDICAR VIA ALTERNA / SIN SEÑALIZACION / SIN MEDIDAS DE SEGURIDAD (CONSTRUCCIONES O REPARACIONES)',
      'INGERIR ALCOHOL EN LA VIA PUBLICA',
      'OTROS (ESPECIFICAR EN LA SECCIÓN DATOS IMPORTANTES DEL FORMATO OF OCURRENCIAS)',
    ],
  },
  {
    typeId: 19,
    subtypes: [
      'RESCATE Y AUXILIO DE PERSONAS',
      'AUXILIO VIAL',
      'MENORES Y ANCIANOS EN ESTADO DE ABANDONO',
      'APOYO AL VECINO',
      'PERSONAS EXTRAVIADAS, DESAPARECIDAS Y DESORIENTADAS',
      'APOYO AL TURISTA',
      'ENTREVISTA POR CONFLICTO VECINAL',
      'OTROS (ESPECIFICAR EN LA SECCIÓN DATOS IMPORTANTES DEL FORMATO OF OCURRENCIAS)',
    ],
  },
  {
    typeId: 20,
    subtypes: [
      'FISCALIZACIÓN Y OTROS (ESPECIFICAR EN LA SECCIÓN DATOS IMPORTANTES DEL FORMATO OF OCURRENCIAS)',
    ],
  },
  {
    typeId: 21,
    subtypes: [
      'POLICÍA NACIONAL Y OTROS (ESPECIFICAR EN LA SECCIÓN DATOS IMPORTANTES DEL FORMATO OF OCURRENCIAS)',
    ],
  },
  {
    typeId: 22,
    subtypes: [
      'HUAYCOS, INUNDACIONES Y DESPLAZAMIENTOS',
      'OTROS FENOMENOS NATURALES (ESPECIFICAR EN LA SECCIÓN DATOS IMPORTANTES DEL FORMATO OF OCURRENCIAS)',
      'INCENDIOS',
      'AMAGO DE INCENDIOS',
      'FUGA DE GAS Y DERRAME DE SUSTANCIAS TÓXICAS',
      'CAÍDA DE PUENTES',
      'OTROS (ESPECIFICAR EN LA SECCIÓN DATOS IMPORTANTES DEL FORMATO OF OCURRENCIAS)',
    ],
  },
  {
    typeId: 23,
    subtypes: [
      'CORTE DE FLUIDO ELÉCTRICO / AGUA / INTERNET /GAS / TELEFONO',
      'ANIEGOS Y/O PROBLEMAS DE DESAGUE',
      'SEMÁFOROS APAGADOS O CON DESPERFECTOS',
      'CAÍDA DE POSTES, CABLES, ÁRBOLES U OTROS',
      'VIVENDAS COLAPSADAS',
      'BUZONES SIN TAPA',
      'TRABAJO DE TERCEROS (INFORMAL Y/O SIN CONDICIONES DE SEGURIDAD)',
      'OTROS',
    ],
  },
  {
    typeId: 24,
    subtypes: [
      'PARQUES Y CALLES SIN ILUMINACIÓN O DEFICIENTE',
      'OBRAS INCONCLUSAS EN LA VIA PÙBLICA',
      'CONSTRUCCIONES ABANDONADAS',
      'VIAS SEMI OBSTRUIDAS (POR BACHES PROFUNDOS O GRAN CONGESTIÓN VEHICULAR)',
      'MOBILIARIO URBANO DETERIORADO Y/O FALTA DE MANTENIMIENTO',
      'VENTA DE MERCADERIA USADA (CACHINAS)',
      'TALLERES EN LA VIA PÙBLICA',
      'OTROS (ESPECIFICAR EN LA SECCIÓN DATOS IMPORTANTES DEL FORMATO OF OCURRENCIAS)',
    ],
  },
  {
    typeId: 25,
    subtypes: [
      'SUICIDIO',
      'INTENTO DE SUICIDIO',
      'MUERTE REPENTINA Y/O NATURAL (ESPECIFICAR EN LA SECCIÓN DATOS IMPORTANTES DEL FORMATO OF OCURRENCIAS)',
      'OTROS (ESPECIFICAR EN LA SECCIÓN DATOS IMPORTANTES DEL FORMATO OF OCURRENCIAS)',
    ],
  },
  {
    typeId: 26,
    subtypes: [
      'OPERATIVO PREVENTIVO',
      'PROTECCIÒN ESCOLAR',
      'ACELERAMIENTO Y DESCONGESTION VEHICULAR',
      'OTROS OPERATIVOS MUNICIPALES (ESPECIFICAR EN LA SECCIÓN DATOS IMPORTANTES DEL FORMATO OF OCURRENCIAS)',
    ],
  },
  {
    typeId: 27,
    subtypes: [
      'EN APOYO A LA PNP EN PROGRAMAS PREVENTIVOS (ESPECIFICAR LA SECCIÓN DATOS IMPORTANTES DEL FORMATO OF OCURRENCIAS)',
      'APOYO A OTRAS ENTIDADES EN PROGRAMAS PREVENTIVOS (ESPECIFICAR EN LA SECCIÓN DATOS IMPORTANTES DEL FORMATO OF OCURRENCIAS)',
      'SERENAZGO SIN FRONTERAS',
      'PATRULLAJE MIXTO (SERENAZGO, JUNTAS VECINALES Y PNP)',
      'CONTACTO Y CONTROL CIUDADANO',
      'OTROS (ESPECIFICAR EN LA SECCIÓN DATOS IMPORTANTES DEL FORMATO OF OCURRENCIAS)',
    ],
  },
];
